version: "3.9"
services:
  application:
    container_name: application
    build: ./app
    ports:
      - 3000:3000
    environment:
      - REDIS_URL=redis://cache
  redis:
    image: redis
    container_name: cache
    expose:
    - 6379